name: Builds

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  linux_physmon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add pseudo output
        run: mkdir physmon && cp physmon.zip physmon/

      - name: Save PR number
        if: ${{ github.event_name == "pull_request" }}
        env:
          PR_URL: ${{ github.event.pull_request.url }}
        run: |
          echo $PR_URL > physmon/pr_url

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: physmon
          path: physmon

