name: Builds

on:
  push:
  pull_request:
    branches:
      - main
      - 'release/**'

jobs:
  linux_physmon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Add pseudo output
        # run: mkdir physmon && cp src_physmon.zip physmon/
        run: unzip src_physmon.zip

      - name: Save PR number
        if: ${{ github.event_name == 'pull_request' }}
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          echo $PR_NUMBER > physmon/pr_number

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: physmon
          path: physmon

